### ISSUE TITLE
如何把这项目放上production

### ISSUE THREAD

**Issue by shern91** [allan2coder/VUE2-SPA-Tutorial#3]
(｡･∀･)ﾉﾞ嗨你好，我目前正在试着学做Vue2 SPA, 在github上找到这项目，clone了后在电脑上可以运行，可是我想把这项目放上服务器（我用着heroku, 目前只会这个），可是却发现application error

`2017-05-19T03:22:41.424890+00:00 app[web.1]: npm ERR! Exit status 1
2017-05-19T03:22:41.406018+00:00 app[web.1]:     at tryModuleLoad (module.js:447:12)
2017-05-19T03:22:41.426455+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2017-05-19T03:22:41.424455+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-05-19T03:22:41.406018+00:00 app[web.1]:     at Function.Module._load (module.js:439:3)
2017-05-19T03:22:41.426575+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-05-19T03_22_41_413Z-debug.log
2017-05-19T03:22:41.525580+00:00 heroku[web.1]: State changed from starting to crashed
2017-05-19T03:23:09.679532+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=simplevue.herokuapp.com request_id=9644c2a8-e87f-4856-90ac-82a2ddf8bb6c fwd="121.122.29.117" dyno= connect= service= status=503 bytes= protocol=https
2017-05-19T03:23:10.126194+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=simplevue.herokuapp.com request_id=2b71a5c2-3e42-4869-96b4-77c83f84fdbd fwd="121.122.29.117" dyno= connect= service= status=503 bytes= protocol=https
2017-05-19T03:25:56.731608+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=simplevue.herokuapp.com request_id=57c16b61-c09b-4d65-a0aa-32abb3dc6601 fwd="121.122.29.117" dyno= connect= service= status=503 bytes= protocol=https
2017-05-19T03:25:57.474399+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=simplevue.herokuapp.com request_id=a309e637-0d9f-42e9-ad04-1393e92913af fwd="121.122.29.117" dyno= connect= service= status=503 bytes= protocol=https`

查看了log，不是很懂，可以请问大大这是什么问题吗？

**Comment by allan2coder** [comment]
执行npm run build，生成的静态文件static，放在服务器上。
起的服务以static文件为根目录。

你是这么做的么？

**Comment by shern91** [comment]
我一开始是clone，git add remote 你的项目去我的heroku project, 执行 npm run build, git add & commit, 再push上heroku，可是就出现error了.
[https://simplevue.herokuapp.com/](这个我目前做的)

**Comment by allan2coder** [comment]
你先在npm run build生成的静态文件内开启服务，本地先跑一下，看是否有问题。

**Comment by shern91** [comment]
好的，谢谢您，我先试看，第一次做有关node.js的项目.

**Comment by shern91** [comment]
经过几天的努力后，已经成功了，不过我是跟着这一个[tutorial](https://github.com/sagarjauhari/vue-deploy-demo)的，不过也谢谢大大提供了这个项目！

**Comment by allan2coder** [comment]
@shern91 非常高兴能给您带来收获。
